image: slepp/arduino

before_script:
    - mkdir -p /usr/local/share/arduino-1.8.5//libraries/KLib
    - cp src/* /usr/local/share/arduino-1.8.5//libraries/KLib/

stages:
    - build
    - test

KLib:
    stage: build
    script:
        - arduino --verbose --verify examples/KLib/KLib.ino

ALed:
    stage: test
    script:
        - arduino --verbose --verify examples/ALed/ALed.ino

AServo:
    stage: test
    script:
        - arduino --verbose --verify examples/AServo/AServo.ino

AStepper:
    stage: test
    script:
        - arduino --verbose --verify examples/AStepper/AStepper.ino

AStorage:
    stage: test
    script:
        - arduino --verbose --verify examples/AStorage/AStorage.ino
